[build]
  command = "pnpm build"
  # Don't set publish directory - let @netlify/plugin-nextjs handle it

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
